# These are supported funding model platforms

# GitHub Sponsors (not available on my region)
# github: jwadow

# Custom donation links
custom:
  - https://app.lava.top/jwadow?tabId=donate
  - https://app.lava.top/jwadow?tabId=subscriptions